name: text_summerization
channels:
  - defaults
dependencies:
  - python
  - transformers
  - transformers[sentencepiece]
  - datasets
  - sacrebleu
  - py7zr
  - pandas
  - nltk
  - tqdm
  - PyYAML
  - matplotlib
  - notebook
  - boto3
  - Jinja2==3.1.2
  - jupyter
  - ipykernel
  - pip
  - pip:
    - rouge_score 
    - torch
    - fastapi==0.78.0
    - mypy-boto3-s3
    - python-box==6.0.2
    - ensure==1.0.2
    - uvicorn==0.18.3
    - -e . 
